### ISSUE TITLE
Please import app instead of hardcoding the path to them

### ISSUE THREAD

**Issue by extsoft** [ogerasymenko/pbc_ogerasymenko#10]
https://github.com/ogerasymenko/pbc_ogerasymenko/blob/8f0da6b225d96175a181f07ff0d8abb9bcd36603/app.py#L10_L12

See details on https://github.com/krizzis/PBC-Vbeliaev/blob/master/app.py

**Comment by ogerasymenko** [comment]
@extsoft Fixed:
https://github.com/ogerasymenko/pbc_ogerasymenko/blob/9523aa2132b1112aed6e74f9c62ce90f5dc35262/app.py#L2
