### ISSUE TITLE
Vagrantfile isn't valid

### ISSUE THREAD

**Issue by extsoft** [ogerasymenko/pbc_ogerasymenko#11]
Please remove `=` from the below line:
https://github.com/ogerasymenko/pbc_ogerasymenko/blob/624a6f6960d3044f0740f1f66da900d3a486e4cb/Vagrantfile#L16

**Comment by ogerasymenko** [comment]
@extsoft Done: https://github.com/ogerasymenko/pbc_ogerasymenko/blob/7acc9aacc648c8b1b561772a2cb86eca14e2d9d0/Vagrantfile#L16
