### ISSUE TITLE
Grid installation has to be a part of a test, not a fixture

### ISSUE THREAD

**Issue by extsoft** [ogerasymenko/pbc_ogerasymenko#14]
https://github.com/ogerasymenko/pbc_ogerasymenko/blob/f10e4a84a205646cc411f0b5fd404be5be8a059b/pbc/sg/conftest.py#L8_L10

**Comment by ogerasymenko** [comment]
@extsoft I'm not agree with you - I'm expect, what selenium will be running before test

**Comment by extsoft** [comment]
@ogerasymenko okay, then close the issue.
